---
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    hostname: plex
    ports:
      # # ? host:container
      - 32400:32400 # Web interface and player communication.
      - 1900:1900/udp # DLNA discovery.
      # - 5353:5353/udp # (Optional) mDNS/Bonjour for service discovery.
      - 8324:8324 # Plex Companion service.
      - 32410:32410/udp # GDM network discovery.
      - 32412:32412/udp # GDM network discovery.
      - 32413:32413/udp # GDM network discovery.
      - 32414:32414/udp # GDM network discovery.
      - 32469:32469 # Remote access.
    environment:
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${DATA_SHARE}/plex-config
        target: /config
      - type: bind
        source: ${MEDIA_SHARE}
        target: /Media
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 7940M
        reservations:
          memory: "268435456"
    restart: unless-stopped
    cpu_shares: 90
    privileged: false
    network_mode: "host"
    environment:
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${DATA_SHARE}/plex-config
        target: /config
      - type: bind
        source: ${MEDIA_SHARE}
        target: /Media
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 7940M
        reservations:
          memory: "268435456"
    restart: unless-stopped
    cpu_shares: 90
    privileged: false
    network_mode: "host"
