services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    hostname: plex
    environment:
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - type: bind
        source: ${DATA_SHARE}/plex-config
        target: /config
      - type: bind
        source: ${MEDIA_SHARE}
        target: /Media
    restart: unless-stopped
    network_mode: host  # Use host network for external access
    networks:
      docker_internal:  # Custom-named internal network for container communication
        aliases:
          - plex
    deploy:
      resources:
        limits:
          memory: 7940M
        reservations:
          memory: "268435456"
    cpu_shares: 90
    privileged: false

networks:
  docker_internal:  # Custom user-defined network for inter-container communication
    driver: bridge
