
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PGID}
      - PGID=${PUID}
      - TZ=${TZ}
      - NEXTCLOUD_TRUSTED_DOMAINS=qnap 10.0.40.240 fabricesemti.dev 127.0.0.1 localhost
      
    volumes:
      - ${DATA_SHARE}/nextcloud-data/config:/config
      - ${DATA_SHARE}/nextcloud-data/data:/data
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: unless-stopped
