networks:
  # Create this network outside of the stack
  docker_database_network:
    external: true

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:apache
    hostname: nextcloud
    ports:
      - '10020:80'
      - '10023:443'
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
    volumes:
      - ${DATA_SHARE}/nextcloud-config/html:/var/www/html
      - ${DATA_SHARE}/nextcloud-config/custom_apps:/var/www/html/custom_apps
      - ${DATA_SHARE}/nextcloud-config/config:/var/www/html/config
      - ${DATA_SHARE}/nextcloud-data:/var/www/html/data
    restart: unless-stopped
    networks:
      - docker_database_network
    depends_on:
      - nextcloud_db

  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb:10.6
    hostname: nextcloud_db
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATA_SHARE}/nextcloud-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - docker_database_network 