## Access stack on port 14333
## Provide token via GUI! (see 1Password for it's value!)

## Environment variables:
## DATA_SHARE

name: cloudflared

services:
  cloudflared:
    container_name: cloudflared
    image: wisdomsky/cloudflared-web:latest
    ports:
      - target: 14333
        published: "14333"
        protocol: tcp
    restart: unless-stopped
   
    volumes:
      - type: bind
        source: ${DATA_SHARE}/cloudflared/config
        target: /config
    network_mode: host
    privileged: false
