---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks/

# /////////////////////////////////////// HOME TAB

- ㅤ:
    - Youtube:
        - abbr: YT
          href: https://youtube.com/
    - ChatGPT:
        - abbr: GPT
          href: https://chat.openai.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Gmail:
        - abbr: GM
          href: https://gmail.com/

- Shopping:
    - Amazon:
        - abbr: AMZ
          href: https://amazon.co.uk/
    - Ebay:
        - abbr: EB
          href: https://ebay.co.uk/

- Development:
    - Github:
        - abbr: GH
          href: https://github.com/

# /////////////////////////////////////// MEDIA & DOWNLOADS TAB

- Public Trackers:
    - RARBG ・ Public General:
        - abbr: RAR
          href: https://therarbg.to/
    - 1337x ・ Public General:
        - abbr: LT
          href: https://1337x.to/
    - Nyaa ・ Public Anime:
        - abbr: AB
          href: https://nyaa.si/
